
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from "sonner";

const SUPABASE_URL = "https://vqnvjmllbmzwmkfvgxvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbnZqbWxsYm16d21rZnZneHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzEwMzIsImV4cCI6MjA2MDQwNzAzMn0.jkEWqvGPLZGgOcJ3Stfnc2t-nJ5ymFv7ZGSQTYXAdII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    storageKey: 'supabase_auth_token',
    detectSessionInUrl: true,
  }
});

// Log to help debugging
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Evento de autenticación:', event, session ? 'Usuario autenticado' : 'Sin sesión');
  if (event === 'SIGNED_OUT') {
    toast.info("Ha cerrado sesión correctamente");
  } else if (event === 'SIGNED_IN') {
    toast.success("Sesión iniciada correctamente");
  } else if (event === 'TOKEN_REFRESHED') {
    console.log("Token de sesión actualizado");
  }
});

// Helper to check if a session is active and refresh it
export const getActiveSession = async () => {
  try {
    // Get current session
    const { data: { session } } = await supabase.auth.getSession();
    
    // If there's a session, try to refresh it
    if (session) {
      const { error: refreshError } = await supabase.auth.refreshSession();
      if (refreshError) {
        console.warn("Error al refrescar la sesión:", refreshError.message);
        // If session is no longer valid, return null
        if (refreshError.message.includes("JWT expired")) {
          toast.error("Su sesión ha expirado, por favor inicie sesión nuevamente");
          await supabase.auth.signOut();
          return null;
        }
      }
      
      const { data } = await supabase.auth.getSession();
      return data.session;
    }
    
    return session;
  } catch (error) {
    console.error("Error getting/refreshing session:", error);
    return null;
  }
};

// Helper to handle common Supabase errors
export const handleSupabaseError = (error: any, operation: string = "operación") => {
  console.error(`Error en ${operation}:`, error);
  
  if (error.message.includes("JWT expired") || error.message.includes("session")) {
    toast.error(`Su sesión ha expirado, por favor inicie sesión nuevamente`);
  } else if (error.message.includes("violates")) {
    toast.error(`Error: La operación viola restricciones de la base de datos`);
  } else {
    toast.error(`Error en ${operation}: ${error.message}`);
  }
  
  return error;
};
